name: publish_pypi
on: workflow_dispatch
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pdm sync --prod
      - name: Publish package
        run: |
          pdm plugin add pdm-publish
          pdm publish --password ${{ secrets.PYPI_TOKEN }}